--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRUEBA_HABITACION
--------------------------------------------------------

  CREATE TABLE "TESTPERU"."PRUEBA_HABITACION" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"TIPO" NUMBER, 
	"ESTADO" NUMBER, 
	"ACTIVO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU" ;
REM INSERTING into TESTPERU.PRUEBA_HABITACION
SET DEFINE OFF;
Insert into TESTPERU.PRUEBA_HABITACION (ID,NOMBRE,TIPO,ESTADO,ACTIVO) values ('26','HAB-66','3','2','1');
Insert into TESTPERU.PRUEBA_HABITACION (ID,NOMBRE,TIPO,ESTADO,ACTIVO) values ('1','HAB-1','1','1','1');
Insert into TESTPERU.PRUEBA_HABITACION (ID,NOMBRE,TIPO,ESTADO,ACTIVO) values ('2','HAB-2','1','1','1');
Insert into TESTPERU.PRUEBA_HABITACION (ID,NOMBRE,TIPO,ESTADO,ACTIVO) values ('3','HAB-3','2','1','1');
Insert into TESTPERU.PRUEBA_HABITACION (ID,NOMBRE,TIPO,ESTADO,ACTIVO) values ('4','HAB-4','2','1','1');
Insert into TESTPERU.PRUEBA_HABITACION (ID,NOMBRE,TIPO,ESTADO,ACTIVO) values ('5','HAB-5','3','1','1');
Insert into TESTPERU.PRUEBA_HABITACION (ID,NOMBRE,TIPO,ESTADO,ACTIVO) values ('6','HAB-6','3','1','1');
Insert into TESTPERU.PRUEBA_HABITACION (ID,NOMBRE,TIPO,ESTADO,ACTIVO) values ('28','HAB-68','3','1','1');
--------------------------------------------------------
--  DDL for Index PRUEBA_HABITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTPERU"."PRUEBA_HABITACION_PK" ON "TESTPERU"."PRUEBA_HABITACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU" ;
--------------------------------------------------------
--  Constraints for Table PRUEBA_HABITACION
--------------------------------------------------------

  ALTER TABLE "TESTPERU"."PRUEBA_HABITACION" ADD CONSTRAINT "PRUEBA_HABITACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU"  ENABLE;
  ALTER TABLE "TESTPERU"."PRUEBA_HABITACION" MODIFY ("ID" NOT NULL ENABLE);
