--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRUEBA_ESTADOS
--------------------------------------------------------

  CREATE TABLE "TESTPERU"."PRUEBA_ESTADOS" 
   (	"ID" NUMBER, 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU" ;
REM INSERTING into TESTPERU.PRUEBA_ESTADOS
SET DEFINE OFF;
Insert into TESTPERU.PRUEBA_ESTADOS (ID,DESCRIPCION,STATUS) values ('1','LIBRE','1');
Insert into TESTPERU.PRUEBA_ESTADOS (ID,DESCRIPCION,STATUS) values ('2','OCUPADA','1');
Insert into TESTPERU.PRUEBA_ESTADOS (ID,DESCRIPCION,STATUS) values ('3','EN MANTENIMIENTO','1');
Insert into TESTPERU.PRUEBA_ESTADOS (ID,DESCRIPCION,STATUS) values ('4','LIMPIEZA','1');
--------------------------------------------------------
--  DDL for Index PRUEBA_ESTADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTPERU"."PRUEBA_ESTADOS_PK" ON "TESTPERU"."PRUEBA_ESTADOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU" ;
--------------------------------------------------------
--  Constraints for Table PRUEBA_ESTADOS
--------------------------------------------------------

  ALTER TABLE "TESTPERU"."PRUEBA_ESTADOS" ADD CONSTRAINT "PRUEBA_ESTADOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU"  ENABLE;
  ALTER TABLE "TESTPERU"."PRUEBA_ESTADOS" MODIFY ("ID" NOT NULL ENABLE);
