--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRUEBA_TIPO
--------------------------------------------------------

  CREATE TABLE "TESTPERU"."PRUEBA_TIPO" 
   (	"ID" NUMBER, 
	"DESCRIPCION" VARCHAR2(40 BYTE), 
	"OCUPANTES" VARCHAR2(20 BYTE), 
	"ACTIVO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU" ;
REM INSERTING into TESTPERU.PRUEBA_TIPO
SET DEFINE OFF;
Insert into TESTPERU.PRUEBA_TIPO (ID,DESCRIPCION,OCUPANTES,ACTIVO) values ('1','ESTANDAR','3','1');
Insert into TESTPERU.PRUEBA_TIPO (ID,DESCRIPCION,OCUPANTES,ACTIVO) values ('2','NORMAL','4','1');
Insert into TESTPERU.PRUEBA_TIPO (ID,DESCRIPCION,OCUPANTES,ACTIVO) values ('3','SUITE','6','1');
--------------------------------------------------------
--  DDL for Index PRUEBA_TIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTPERU"."PRUEBA_TIPO_PK" ON "TESTPERU"."PRUEBA_TIPO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU" ;
--------------------------------------------------------
--  Constraints for Table PRUEBA_TIPO
--------------------------------------------------------

  ALTER TABLE "TESTPERU"."PRUEBA_TIPO" ADD CONSTRAINT "PRUEBA_TIPO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU"  ENABLE;
  ALTER TABLE "TESTPERU"."PRUEBA_TIPO" MODIFY ("ID" NOT NULL ENABLE);
