--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRUEBA_ROL
--------------------------------------------------------

  CREATE TABLE "TESTPERU"."PRUEBA_ROL" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"TRANSICIONAR" NUMBER, 
	"RESERVAR" NUMBER, 
	"CREAR" NUMBER, 
	"ELIMINAR" NUMBER, 
	"MODIFICAR" NUMBER, 
	"CONSULTAR" NUMBER, 
	"STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU" ;
REM INSERTING into TESTPERU.PRUEBA_ROL
SET DEFINE OFF;
Insert into TESTPERU.PRUEBA_ROL (ID,NOMBRE,TRANSICIONAR,RESERVAR,CREAR,ELIMINAR,MODIFICAR,CONSULTAR,STATUS) values ('1','GERENTE','1','1','1','1','1','1','1');
Insert into TESTPERU.PRUEBA_ROL (ID,NOMBRE,TRANSICIONAR,RESERVAR,CREAR,ELIMINAR,MODIFICAR,CONSULTAR,STATUS) values ('2','RECEPCIONISTA','1','1','0','0','0','1','1');
Insert into TESTPERU.PRUEBA_ROL (ID,NOMBRE,TRANSICIONAR,RESERVAR,CREAR,ELIMINAR,MODIFICAR,CONSULTAR,STATUS) values ('3','CLIENTE','0','1','0','0','0','1','1');
--------------------------------------------------------
--  DDL for Index PRUEBA_ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTPERU"."PRUEBA_ROL_PK" ON "TESTPERU"."PRUEBA_ROL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU" ;
--------------------------------------------------------
--  Constraints for Table PRUEBA_ROL
--------------------------------------------------------

  ALTER TABLE "TESTPERU"."PRUEBA_ROL" ADD CONSTRAINT "PRUEBA_ROL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DAT01_PERU"  ENABLE;
  ALTER TABLE "TESTPERU"."PRUEBA_ROL" MODIFY ("ID" NOT NULL ENABLE);
